/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import control.Controlador;
import java.awt.Color;
import javax.swing.*;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author vicjo
 */
public class AbrirArchivoTexto extends javax.swing.JInternalFrame {

    Controlador objControlador = new Controlador();

    public AbrirArchivoTexto() {
        initComponents();
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaArchivoAbierto = new javax.swing.JTextArea();
        btnSelector = new javax.swing.JButton();
        jpnBtnAceptar = new javax.swing.JPanel();
        lblBtnAceptar = new javax.swing.JLabel();
        jpnBtnCancelar = new javax.swing.JPanel();
        lblBtnCancelar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaArchivoAbierto.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaArchivoAbierto.setColumns(20);
        txtAreaArchivoAbierto.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaArchivoAbierto.setRows(5);
        jScrollPane1.setViewportView(txtAreaArchivoAbierto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 470, 230));

        btnSelector.setBackground(new java.awt.Color(204, 204, 204));
        btnSelector.setForeground(new java.awt.Color(0, 0, 0));
        btnSelector.setText("...");
        btnSelector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSelectorMouseClicked(evt);
            }
        });
        getContentPane().add(btnSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jpnBtnAceptar.setBackground(new java.awt.Color(204, 204, 204));
        jpnBtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnBtnAceptar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBtnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnAceptar.setFont(new java.awt.Font("Roboto Black", 0, 13)); // NOI18N
        lblBtnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        lblBtnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnAceptar.setText("ACEPTAR");
        lblBtnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnAceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnAceptarMouseExited(evt);
            }
        });
        jpnBtnAceptar.add(lblBtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        getContentPane().add(jpnBtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 90, 30));

        jpnBtnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        jpnBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnBtnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBtnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        lblBtnCancelar.setFont(new java.awt.Font("Roboto Black", 0, 13)); // NOI18N
        lblBtnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        lblBtnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnCancelar.setText("CANCELAR");
        lblBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBtnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBtnCancelarMouseExited(evt);
            }
        });
        jpnBtnCancelar.add(lblBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        getContentPane().add(jpnBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSelectorMouseClicked
        String contenidoArchivo = objControlador.abrirArchivo();
        txtAreaArchivoAbierto.setText(contenidoArchivo);
    }//GEN-LAST:event_btnSelectorMouseClicked

    private void lblBtnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnAceptarMouseClicked
        JOptionPane.showMessageDialog(null, objControlador.sobreescribiendo(txtAreaArchivoAbierto.getText()));
        this.dispose();
    }//GEN-LAST:event_lblBtnAceptarMouseClicked

    private void lblBtnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnAceptarMouseEntered
        lblBtnAceptar.setForeground(Color.white);
        jpnBtnAceptar.setBackground(Color.black);
    }//GEN-LAST:event_lblBtnAceptarMouseEntered

    private void lblBtnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnAceptarMouseExited
        lblBtnAceptar.setForeground(Color.black);
        jpnBtnAceptar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblBtnAceptarMouseExited

    private void lblBtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCancelarMouseClicked

    }//GEN-LAST:event_lblBtnCancelarMouseClicked

    private void lblBtnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCancelarMouseEntered
        lblBtnCancelar.setForeground(Color.white);
        jpnBtnCancelar.setBackground(Color.black);
    }//GEN-LAST:event_lblBtnCancelarMouseEntered

    private void lblBtnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnCancelarMouseExited
        lblBtnCancelar.setForeground(Color.black);
        jpnBtnCancelar.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_lblBtnCancelarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelector;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnBtnAceptar;
    private javax.swing.JPanel jpnBtnCancelar;
    private javax.swing.JLabel lblBtnAceptar;
    private javax.swing.JLabel lblBtnCancelar;
    private javax.swing.JTextArea txtAreaArchivoAbierto;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnSelector() {
        return btnSelector;
    }

    public void setBtnSelector(JButton btnSelector) {
        this.btnSelector = btnSelector;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getTxtAreaArchivoAbierto() {
        return txtAreaArchivoAbierto;
    }

    public void setTxtAreaArchivoAbierto(JTextArea txtAreaArchivoAbierto) {
        this.txtAreaArchivoAbierto = txtAreaArchivoAbierto;
    }

    public Controlador getObjControlador() {
        return objControlador;
    }

    public void setObjControlador(Controlador objControlador) {
        this.objControlador = objControlador;
    }

    public JPanel getJpnBtnAceptar() {
        return jpnBtnAceptar;
    }

    public void setJpnBtnAceptar(JPanel jpnBtnAceptar) {
        this.jpnBtnAceptar = jpnBtnAceptar;
    }

    public JPanel getJpnBtnCancelar() {
        return jpnBtnCancelar;
    }

    public void setJpnBtnCancelar(JPanel jpnBtnCancelar) {
        this.jpnBtnCancelar = jpnBtnCancelar;
    }

    public JLabel getLblBtnAceptar() {
        return lblBtnAceptar;
    }

    public void setLblBtnAceptar(JLabel lblBtnAceptar) {
        this.lblBtnAceptar = lblBtnAceptar;
    }

    public JLabel getLblBtnCancelar() {
        return lblBtnCancelar;
    }

    public void setLblBtnCancelar(JLabel lblBtnCancelar) {
        this.lblBtnCancelar = lblBtnCancelar;
    }

}
